# Generated by Django 2.2 on 2021-01-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='status',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='content',
            field=models.TextField(),
        ),
    ]
